name: Run Gosec
on:
  push:
    branches: ["master", "main"]

jobs:
  semgrep:
    name: Semgrep scan
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v2
      - name: Setup SSH Keys and known_hosts
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add - <<< "${{ secrets.SSH_REPO_PRIVATE_KEY }}"
      - name: Checkout custom rules
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: git clone git@github.com:pingvin1341/custom-rulepack.git ../custom-rules/
      - name: Show dirs structure
        run: cd  ../ && ls -la
      - name: Run semgrep in docker
        run: cd ../ && docker run -v $(pwd):/src --workdir /src returntocorp/semgrep-agent:v1 semgrep --config custom-rules/ --include=gosec-pipeline --json gosec-pipeline/ > semgrep.json
      - name: view
        run: cat ../semgrep.json

  gosec:
    name: Gosec scan 
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '-no-fail -fmt sarif -out gosec.sarif ./...'
      - name: view
        run: cat gosec.sarif
  #    - name: Upload file
   #     run: |
    #     curl -v -s --request POST ${{ secrets.REPORT_URL }} \
    #     -H "Content-Type: multipart/form-data" \
    #     -H "Authorization: Token ${{ secrets.API_REPORT_KEY }}" \
    #     -F "file=@gosec.sarif"

  analyze:
    name: Codeql scan
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ['go']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master

  tuflehog:
    runs-on: ubuntu-latest      
    steps:
    - uses: actions/checkout@v2
      with:
       fetch-depth: 0
    - name: trufflehog-actions-scan
      uses: edplato/trufflehog-actions-scan@master
